# Artificial Neural Networks - Forward Propagation

## Introduction

In this lab, we will build a neural network from scratch and code how it performs predictions using forward propagation. Please note that all deep learning libraries have the entire training and prediction processes implemented, so in practice, you wouldn't need to build a neural network from scratch. However, completing this lab will help you better understand neural networks and how they work.


## Objective for this Notebook    
* Build a Neural Network
* Compute Weighted Sum at Each Node
* Compute Node Activation
* Use Forward Propagation to Propagate Data



From the videos, let's recap how a neural network makes predictions through the forward propagation process. Here is a neural network that takes two inputs, has one hidden layer with two nodes, and an output layer with one node.

<img src="http://cocl.us/neural_network_example" alt="Neural Network Example" width="600px">


Let's start by randomly initializing the weights and the biases in the network. We have 6 weights and 3 biases, one for each node in the hidden layer as well as for each node in the output layer.


In [1]:
import numpy as np

weights = np.around(np.random.uniform(size=6), decimals=2)#Initilize weights
bias = np.around(np.random.uniform(size = 3), decimals=2)#Initialize bias

print("weights: \n", weights)
print("bias: \n", bias)

weights: 
 [0.96 0.63 0.46 0.02 0.75 0.76]
bias: 
 [0.32 0.33 0.93]


Now that we have the weights and the biases defined for the network, let's compute the output for a given input, $x_1$ and $x_2$.


In [2]:
x_1 = 0.5
x_2 = 0.85

print("x1 is {} and x2 is {}".format(x_1, x_2))

x1 is 0.5 and x2 is 0.85


Let's start by computing the weighted sum of the inputs, $z_{1, 1}$, at the first node of the hidden layer.

In [3]:
z_11 = x_1 * weights[0] + x_2 * weights[1]  + bias[0]
print('The weighted sum of the inputs at the first node in the hidden layer is {}'
      .format(np.around(z_11, decimals=4)))

The weighted sum of the inputs at the first node in the hidden layer is 1.3355


Next, let's compute the weighted sum of the inputs, $z_{1, 2}$, at the second node of the hidden layer. Assign the value to **z_12**.


In [4]:
z_12 = x_1 * weights[2] + x_2 *  weights[3] + bias[1]
print('The weighted sum of the inputs at the second node in the hidden layer is {}'.format(np.around(z_12,decimals=4)))

The weighted sum of the inputs at the second node in the hidden layer is 0.577


Next, assuming a sigmoid activation function, let's compute the activation of the first node, $a_{1, 1}$, in the hidden layer.


In [5]:
a_11 = 1.0/(1.0 + np.exp(-z_11))

print('The activation of the first node in the hidden layer is {}'
      .format(np.around(a_11,decimals=4)))

The activation of the first node in the hidden layer is 0.7917


In [6]:
a_12 = 1.0/(1.0 + np.exp(-z_12))
print('The activation of the second node in the hidden layer is {}'
      .format(np.around(a_12,decimals=4)))

The activation of the second node in the hidden layer is 0.6404


Now these activations will serve as the inputs to the output layer. So, let's compute the weighted sum of these inputs to the node in the output layer. Assign the value to **z_2**.


In [7]:
z_2 = a_11 * weights[4] + a_12 * weights[5] + bias[2]
print('The weighted sum of the inputs at the first node in the second hidden layer is {}'.format(np.around(z_2,decimals=4)))

The weighted sum of the inputs at the first node in the second hidden layer is 2.0105


In [8]:
a_2 = 1.0/(1.0 + np.exp(-z_2))
print('The activation of the second node in the hidden layer is {}'
      .format(np.around(a_2,decimals=4)))

The activation of the second node in the hidden layer is 0.8819


## Build a Neural Network


Let's start by formally defining the structure of the network.


In [9]:
# number of inputs
n =2

#number of hodden layers
hidden_layers = 2

#number of nodes each layer
m = [2,2]

#number of outputs layer nodes
output_nodes = 1

Now that we defined the structure of the network, let's go ahead and inititailize the weights and the biases in the network to random numbers. In order to be able to initialize the weights and the biases to random numbers, we will need to import the **Numpy** library.


In [10]:
import numpy as np

num_nodes_previous = n # number of nodes in the previous layer
network = {} # network define as empty dict

for layer in range (hidden_layers+1):
    if (layer == (hidden_layers)):
        layer_name = 'output'
        num_nodes = output_nodes
    
    else:
        layer_name = 'layer_{}'.format(layer+1)
        num_nodes = m[layer]
        
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weight': np.around(np.random.uniform(size = num_nodes_previous),decimals=4),
            'bias': np.around(np.random.uniform(size = 1),decimals=4)
        }
    num_nodes_previous = num_nodes

print(network)

{'layer_1': {'node_1': {'weight': array([0.8005, 0.985 ]), 'bias': array([0.778])}, 'node_2': {'weight': array([0.0873, 0.1884]), 'bias': array([0.1191])}}, 'layer_2': {'node_1': {'weight': array([0.6566, 0.3916]), 'bias': array([0.9238])}, 'node_2': {'weight': array([0.6774, 0.3006]), 'bias': array([0.8898])}}, 'output': {'node_1': {'weight': array([0.7938, 0.7921]), 'bias': array([0.9876])}}}


So for any layer with n nodes, there are always exactly n biases — one per node, no sharing.
The bias is like each node's personal adjustment knob — it shifts the output up or down independently of the inputs.

Awesome! So now with the above code, we are able to initialize the weights and the biases pertaining to any network of any number of hidden layers and number of nodes in each layer. But let's put this code in a function so that we are able to repetitively execute all this code whenever we want to construct a neural network.


In [11]:
def initialize_network(num_inputs, num_hidden_layers, num_hidden_nodes, num_outputs):
    
    num_prev_nodes = num_inputs
    
    for layer in range(num_hidden_layers+1):
        if (layer == num_hidden_layers):
            layer_name = 'output'
            num_nodes = num_outputs
            
        else:
            layer_name = 'layer_{}'.format(layer+1)
            num_nodes = num_hidden_nodes[layer]
        
        network[layer_name] = {}
          
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node + 1)
            network[layer_name][node_name] = {
                'weight': np.around(np.random.uniform(size=num_prev_nodes),decimals=4),
                'bias': np.around(np.random.uniform(size=1),decimals=4)
            }
        
        num_prev_nodes = num_nodes

    return network
            

In [12]:
##initialize a samll network

small_network = initialize_network(5,3,[3,2,3],1)
small_network

{'layer_1': {'node_1': {'weight': array([0.7807, 0.711 , 0.8816, 0.8661, 0.3936]),
   'bias': array([0.4439])},
  'node_2': {'weight': array([0.0774, 0.3904, 0.014 , 0.4129, 0.6029]),
   'bias': array([0.0347])},
  'node_3': {'weight': array([0.2233, 0.9902, 0.9806, 0.4181, 0.3656]),
   'bias': array([0.0685])}},
 'layer_2': {'node_1': {'weight': array([0.7504, 0.0068, 0.8534]),
   'bias': array([0.3271])},
  'node_2': {'weight': array([0.1695, 0.2468, 0.6224]),
   'bias': array([0.5356])}},
 'output': {'node_1': {'weight': array([0.7362, 0.1073, 0.3774]),
   'bias': array([0.0514])}},
 'layer_3': {'node_1': {'weight': array([0.1738, 0.1402]),
   'bias': array([0.5727])},
  'node_2': {'weight': array([0.7851, 0.7064]), 'bias': array([0.3785])},
  'node_3': {'weight': array([0.6716, 0.8938]), 'bias': array([0.7281])}}}

## Compute Weighted Sum at Each Node
The weighted sum at each node is computed as the dot product of the inputs and the weights plus the bias. So let's create a function called *compute_weighted_sum* that does just that.


In [25]:
def weighted_sum (inputs, weights, bias):
    return np.sum(inputs * weights) + bias

In [27]:
# lets generate 5 inputs randomly
np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=4)
print("Inputs of the network are {}".format(inputs))

Inputs of the network are [0.1542 0.74   0.2633 0.5337 0.0146]


#### Use the *compute_weighted_sum* function to compute the weighted sum at the first node in the first hidden layer.


In [33]:
node_weights = small_network['layer_1']['node_1']['weight']
node_bias = small_network['layer_1']['node_1']['bias']

weight_sum = weighted_sum(inputs, node_weights,node_bias) 
print("The weighted sum at the first node in the hidden layer is {}".format(np.around(weight_sum[0],decimals=4)))
weight_sum

The weighted sum at the first node in the hidden layer is 1.7905


array([1.79053335])

## Compute Node Activation


Recall that the output of each node is simply a non-linear tranformation of the weighted sum. We use activation functions for this mapping. Let's use the sigmoid function as the activation function here. So let's define a function that takes a weighted sum as input and returns the non-linear transformation of the input using the sigmoid function.


In [29]:
def node_activation (node_weight_sum):
    return (1.0/(1.0 + np.exp(-1 * node_weight_sum)))

#### Use the *node_activation* function to compute the output of the first node in the first hidden layer.


In [32]:
node_outputs = node_activation(weighted_sum(inputs, node_weights, node_bias))
print("The activation value at the first node in the hidden layer is {}".format(np.around(node_outputs[0],decimals=4)))
node_outputs

The activation value at the first node in the hidden layer is 0.857


array([0.85699265])