# Creating an NLP Data Loader 


In [25]:
import torchtext
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from torch.nn.utils.rnn import pad_sequence

### Custom data set and data loader in PyTorch
In this code snippet, you will see how to create a custom data set and use the DataLoader class in PyTorch. The data set consists of a list of random sentences, and the objective is to create batches of sentences for further processing, such as training a neural network model.

You will begin by defining a custom data set called CustomDataset. This data set inherits from the `torch.utils.data.Dataset` class and is initialized with a list of sentences. The data set comprises two essential methods:

- __init__(self, sentences): Initializes the data set with a list of sentences.
- __getitem__(self, idx): Retrieves an item (in this case, a sentence) at a specific index, idx.

Next, you create an instance of your custom data set (custom_dataset) by passing in the list of sentences. Additionally, you can specify a batch size (batch_size), which determines how many sentences will be grouped together in each batch during data loading.

You will then create a DataLoader (dataloader) by providing your custom data set and batch size to the torch.utils.data.DataLoader class. Furthermore, you set shuffle=True, indicating that the sentences will be randomly shuffled before being divided into batches. This shuffling is particularly useful for training deep learning models, as it prevents the model from learning patterns based on the order of the data.

Finally, you iterate through the DataLoader to demonstrate how data is loaded in batches. In this code, you will see that batch size is set to 2, meaning that each batch will contain two sentences. The DataLoader efficiently manages the loading of data in batches, making it suitable for training deep learning models.

During iteration, the sentences in each batch are printed to illustrate how the DataLoader groups and presents the data. This code snippet provides a fundamental example of how to set up a custom data set and data loader in PyTorch, which is a common practice in deep learning workflows.


In [18]:
sentences = [
    "I woke up early today and went for a walk.",
    "The weather is really nice this morning.",
    "I forgot to bring my charger to work.",
    "Let's grab something to eat later.",
    "She is watching a movie in the living room.",
    "I need to finish my assignment tonight.",
    "He called me yesterday but I missed it.",
    "We are planning to go on a trip next month.",
    "I am feeling a bit tired today.",
    "Can you help me with this problem?",
    "The food at that restaurant was amazing.",
    "I will call you back in a few minutes.",
    "They are playing football in the park.",
    "I have an important meeting tomorrow.",
    "This book is really interesting to read."
]

# define a custom dataset
class CustomDataset (Dataset):
    
    def __init__(self,sentences):
        self.sentences = sentences
    
    def __len__(self):
        return len(self.sentences)
    
    def __getitem__(self, index):
        return self.sentences[index]
    
#create an object of CustomeDataset class
custom_dataset = CustomDataset(sentences)
        

In [19]:
batch_size = 2

# create and dataloader instance
data_loader = DataLoader(dataset=custom_dataset, batch_size=batch_size, shuffle=True)

for batch in data_loader:
    print(batch)

['I need to finish my assignment tonight.', 'They are playing football in the park.']
['We are planning to go on a trip next month.', 'I am feeling a bit tired today.']
['She is watching a movie in the living room.', 'He called me yesterday but I missed it.']
['I have an important meeting tomorrow.', 'I will call you back in a few minutes.']
['The food at that restaurant was amazing.', "Let's grab something to eat later."]
['I forgot to bring my charger to work.', 'Can you help me with this problem?']
['I woke up early today and went for a walk.', 'The weather is really nice this morning.']
['This book is really interesting to read.']


## Creating tensors for custom data set

In this code example, you will see the creation of a custom data set for natural language processing (NLP) tasks using PyTorch. The data set consists of a list of sentences, and your goal is to preprocess these sentences, tokenize them, and convert them into tensors of token indices for use in NLP models. Let's break down the code step by step.

The sentences and the CustomDataset class are used in the same way as in the previous code snippet. The changes made to the CustomDataset class are as follows:

- __init__: The constructor takes a list of sentences, a tokenizer function, and a vocabulary (vocab) as input.
- __len__: This method returns the total number of samples in the data set.
- __getitem__: This method is responsible for processing a single sample. It tokenizes the sentence using the provided tokenizer and then converts the tokens into tensor indices using the vocabulary.

You can define a tokenizer using the `get_tokenizer` function with the `basic_english` option. Tokenization is the process of splitting a text into individual tokens or words. Next, you build a vocabulary from the sentences. You use the `build_vocab_from_iterator` function to construct the vocabulary from the tokenized sentences.

You can create an instance of your custom data set, passing in the sentences, tokenizer, and vocabulary. Finally, you print the length of the custom data set and sample items from the data set for illustration.


In [22]:
sentences_2 = [
    "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
    "Fame's a fickle friend, Harry.",
    "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    "Soon we must all face the choice between what is right and what is easy.",
    "Youth can not know how age thinks and feels. But old men are guilty if they forget what it was to be young.",
    "You are awesome!"
]

In [106]:
sentences = [
    "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
    "Fame's a fickle friend, Harry.",
    "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    "Soon we must all face the choice between what is right and what is easy.",
    "Youth can not know how age thinks and feels. But old men are guilty if they forget what it was to be young.",
    "You are awesome!"
]

class CustomDataset(Dataset):
    
    def __init__(self, sentences,tokenizer, vocab):
        self.sentences = sentences
        self.tokenizer = tokenizer
        self.vocab = vocab
    
    def __len__(self):
        return len(self.sentences)
    
    def __getitem__(self, index):
        tokens = self.tokenizer(sentences[index])
        tensor_indices = [self.vocab[token] for token in tokens]
        return torch.tensor(tensor_indices)
    
# define tokenizer
tokenizer = get_tokenizer("basic_english")

# define vocab
vocab = build_vocab_from_iterator(map(tokenizer,sentences))

# create a CustomDataset instance
custom_dataset = CustomDataset(sentences,tokenizer, vocab)

print("length of dataset:", custom_dataset.__len__())
print("Sample Items:")
for i in range(6):
    sample_item = custom_dataset[i]
    print(f"Item {i + 1}: {sample_item}")

length of dataset: 6
Sample Items:
Item 1: tensor([11, 19, 63, 17, 13,  2,  3, 47,  6, 16, 45,  0, 55,  3, 41, 46, 24, 10,
        43, 61,  9, 44,  0, 14,  9, 33,  1])
Item 2: tensor([35,  6, 16,  3, 38, 40,  0,  8,  1])
Item 3: tensor([12,  5, 15, 31,  0,  8,  0, 57, 53,  2, 18, 62,  4,  0, 36, 49, 56, 15,
        21,  1])
Item 4: tensor([54, 18, 50, 23, 34, 58, 30, 27,  2,  5, 52,  7,  2,  5, 32,  1])
Item 5: tensor([66, 29, 14, 13, 10, 22, 60,  7, 37,  1, 28, 51, 48,  4, 42, 11, 59, 39,
         2, 12, 64, 17, 26, 65,  1])
Item 6: tensor([19,  4, 25, 20])


#### build the data loader

In [24]:
batch_size = 3

# build a dataloader
data_loader = DataLoader(dataset=custom_dataset, batch_size=batch_size, shuffle=True)

for bacth in data_loader:
    print(batch)

RuntimeError: stack expects each tensor to be equal size, but got [27] at entry 0 and [4] at entry 1

You will encounter an error when attempting to create batches for the tensors. This error arises because the tensor batches have unequal lengths. The data loader is using the default `collate_function`, which requires tensors to have equal lengths. You can define your own `collate_function` and pass the data into it to establish your own rules. Typically, to address the issue of unequal tensor lengths, you employ data padding. This will be demonstrated in the following section.


In [73]:
## define a custome collate function

def collate_fn(batch):
    padded_batch = pad_sequence(batch,batch_first=True, padding_value= 0)
    return padded_batch

In [74]:
data_loader = DataLoader(custom_dataset,batch_size=2, shuffle=True, collate_fn=collate_fn)

for batch in data_loader:
    for row in batch:
            words = [vocab.get_itos()[idx] for idx in row]
            print(words)

['youth', 'can', 'not', 'know', 'how', 'age', 'thinks', 'and', 'feels', '.', 'but', 'old', 'men', 'are', 'guilty', 'if', 'they', 'forget', 'what', 'it', 'was', 'to', 'be', 'young', '.']
['fame', "'", 's', 'a', 'fickle', 'friend', ',', 'harry', '.', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',']
['it', 'is', 'our', 'choices', ',', 'harry', ',', 'that', 'show', 'what', 'we', 'truly', 'are', ',', 'far', 'more', 'than', 'our', 'abilities', '.']
['soon', 'we', 'must', 'all', 'face', 'the', 'choice', 'between', 'what', 'is', 'right', 'and', 'what', 'is', 'easy', '.', ',', ',', ',', ',']
['if', 'you', 'want', 'to', 'know', 'what', 'a', 'man', "'", 's', 'like', ',', 'take', 'a', 'good', 'look', 'at', 'how', 'he', 'treats', 'his', 'inferiors', ',', 'not', 'his', 'equals', '.']
['you', 'are', 'awesome', '!', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',']


In [75]:
## check whether each batch have same length
for batch in  data_loader:
    print(batch)
    print("Length of sequences in batch: ", batch.shape[1])
    

tensor([[12,  5, 15, 31,  0,  8,  0, 57, 53,  2, 18, 62,  4,  0, 36, 49, 56, 15,
         21,  1],
        [54, 18, 50, 23, 34, 58, 30, 27,  2,  5, 52,  7,  2,  5, 32,  1,  0,  0,
          0,  0]])
Length of sequences in batch:  20
tensor([[19,  4, 25, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11, 19, 63, 17, 13,  2,  3, 47,  6, 16, 45,  0, 55,  3, 41, 46, 24, 10,
         43, 61,  9, 44,  0, 14,  9, 33,  1]])
Length of sequences in batch:  27
tensor([[66, 29, 14, 13, 10, 22, 60,  7, 37,  1, 28, 51, 48,  4, 42, 11, 59, 39,
          2, 12, 64, 17, 26, 65,  1],
        [35,  6, 16,  3, 38, 40,  0,  8,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0]])
Length of sequences in batch:  25


This means, each batch is padded to same length independently. so that means in each sequence is padded to the maximum sequence length in the batch. This process is done each batch. Like this is an **internal process** for rach batch 

You will see that each batch has a fixed size for all the sequences within the batch.

You also have the option to utilize the collate function for tasks such as tokenization, converting tokenized indices, and transforming the result into a tensor. It's important to note that the original data set remains untouched by these transformations.


In [104]:
new_sentences = [
    "I am going to the supermarket to buy some groceries.",
    "She is studying computer engineering at university.",
    "We had a great time at the beach yesterday.",
    "He forgot to set his alarm and woke up late.",
    "The train was delayed بسبب heavy rain this morning.",
    "I like to drink coffee while reading a book.",
    "They are planning a surprise birthday party for her.",
    "My laptop battery drains very quickly these days.",
    "We should go for a walk in the evening.",
    "He is learning Python and building small projects.",
    "The food at that restaurant was really delicious.",
    "I need to finish my assignment before the deadline.",
    "She called me but I missed her call.",
    "It is important to stay hydrated during hot weather.",
    "They are playing cricket in the playground.",
    "I watched an interesting documentary last night.",
    "He is fixing his car in the garage.",
    "We are waiting for the bus at the station.",
    "I forgot where I kept my keys.",
    "She enjoys listening to music while working."
]

In [80]:
# define Custome Dataset class
class NewCustomDataset (Dataset):
    
    def __init__(self, sentences):
        self.senetences = sentences
    
    def __len__(self):
        return len(self.senetences)

    def __getitem__(self, index):
        return self.senetences[index]
    
    

In [111]:
newCustomDataset = NewCustomDataset(new_sentences)
new_tokenizer = get_tokenizer("basic_english")
new_vocab = build_vocab_from_iterator(map(new_tokenizer,new_sentences))

In [112]:
def collate_fn(batch):
    # Tokenize each sample in the batch using the specified tokenizer
    tensor_batch = []
    for sample in batch:
        tokens = new_tokenizer(sample)
        # Convert tokens to vocabulary indices and create a tensor for each sample
        tensor_batch.append(torch.tensor([new_vocab[token] for token in tokens]))

    # Pad sequences within the batch to have equal lengths using pad_sequence
    # batch_first=True ensures that the tensors have shape (batch_size, max_sequence_length)
    padded_batch = pad_sequence(tensor_batch, batch_first=True)
    
    # Return the padded batch
    return padded_batch

In [113]:
# define dataloader object
new_data_loader = DataLoader(newCustomDataset, batch_size=2,shuffle=True, collate_fn=collate_fn)

In [115]:
for batch in new_data_loader: 
    print(batch)
    print("Length of samples:",len(batch))

tensor([[  2,  15, 112,   2,  66,  11,  67,   0,   0,   0],
        [ 65,   6,  63,   3,  96,  62,  47,  61, 111,   0]])
Length of samples: 2
tensor([[  1,  53,   5, 100,  90,  19,  89,  43,   0,   0,   0],
        [  9,  15,   3,  91,  17,  21,  14, 113, 106,  70,   0]])
Length of samples: 2
tensor([[ 2, 22, 56,  3,  1, 98,  3, 33, 94, 58,  0],
        [ 9,  6, 52, 17, 36, 10,  1, 54,  0,  0,  0]])
Length of samples: 2
tensor([[  1, 104,  19,  42, 116,  60,  87, 102,  76,   0],
        [ 12,  35,  74,  32,   2,  75,  16,  34,   0,   0]])
Length of samples: 2
tensor([[  2,  78,   3,  51,  11,  24,  27,   1,  41,   0],
        [  2, 110,  23,  64,  44,  69,  79,   0,   0,   0]])
Length of samples: 2
tensor([[ 13,  59,   4,  57, 103,   5,   1,  26, 115,   0],
        [  2,  72,   3,  46,  37,  20,  88,   4,  29,   0]])
Length of samples: 2
tensor([[ 12,   6,  97,  38,  48,   5, 105,   0],
        [ 18,   7,  83,  39,  10,   1,  82,   0]])
Length of samples: 2
tensor([[ 9,  6, 71, 85, 14,

## Part II

Create a data loader with a collate function that processes batches of French text (provided below). Sort the data set on sequences length. Then tokenize, numericalize and pad the sequences. Sorting the sequences will minimize the number of `<PAD>`tokens added to the sequences, which enhances the model's performance. Prepare the data in batches of size 4 and print them.


In [116]:
french_text = ["Ceci est une phrase.",
    "C'est un autre exemple de phrase.",
    "Voici une troisième phrase.",
    "Il fait beau aujourd'hui.",
    "J'aime beaucoup la cuisine française.",
    "Quel est ton plat préféré ?",
    "Je t'adore.",
    "Bon appétit !",
    "Je suis en train d'apprendre le français.",
    "Nous devons partir tôt demain matin.",
    "Je suis heureux.",
    "Le film était vraiment captivant !",
    "Je suis là.",
    "Je ne sais pas.",
    "Je suis fatigué après une longue journée de travail.",
    "Est-ce que tu as des projets pour le week-end ?",
    "Je vais chez le médecin cet après-midi.",
    "La musique adoucit les mœurs.",
    "Je dois acheter du pain et du lait.",
    "Il y a beaucoup de monde dans cette ville.",
    "Merci beaucoup !",
    "Au revoir !",
    "Je suis ravi de vous rencontrer enfin !",
    "Les vacances sont toujours trop courtes.",
    "Je suis en retard.",
    "Félicitations pour ton nouveau travail !",
    "Je suis désolé, je ne peux pas venir à la réunion.",
    "À quelle heure est le prochain train ?",
    "Bonjour !",
    "C'est génial !"]

In [117]:
class FrenchDataset (Dataset):
    
    def __init__(self,sentences):
        self.sentences = sentences
    
    def __len__(self):
        return len(self.sentences)
    
    def __getitem__(self, index):
        return self.sentences[index]
    
    